name: Deploy to EC2

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'infrastructure/**'
      - 'docs/**'
      - '*.md'
      - '.gitignore'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ vars.EC2_HOST }}
        username: ${{ vars.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Check if project directory exists, if not clone it
          if [ ! -d "/home/${{ vars.EC2_USERNAME }}/nodejs-simpleapi" ]; then
            cd /home/${{ vars.EC2_USERNAME }}i
            git clone https://github.com/${{ github.repository }}.git nodejs-simpleapi
          fi
          
          cd /home/${{ vars.EC2_USERNAME }}/nodejs-simpleapi
          
          git pull origin main
          npm ci --production

          export PORT=3000
          export NODE_ENV=production
          export LOG_LEVEL=info
          export DATABASE_URL=${{ secrets.APP_DATABASE_URL }}

          pm2 restart nodejs-api || pm2 start npm --name "nodejs-simpleapi" -- start
          pm2 save
          
          # Log current commit for easy reference
          echo "Deployed commit: $(git rev-parse HEAD)"
          pm2 save
          
          # Log current commit for easy reference
          echo "Deployed commit: $(git rev-parse HEAD)"
