name: Node.js CI Test
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'infrastructure/**'

  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 23, 24]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    # - name: Deploy if tests pass
    #   if: success()
    #   run: |
    #     echo "Deploying application..."
    #     # Add your deployment commands here, e.g., npm run deploy
    #     echo "Deployment complete."